function print_error(abs_error, sq_error, l_inf_error, filter_name)
fprintf(['%s', ...
    '\nmean abs_error: %.4f std abs_error: %.4f' ...
    '\nsq_error: %.4f std sq_error: %.4f' ...
    '\nl_inf_error: %.4f\n'], ...
    filter_name, ...
    mean(abs_error), std(abs_error), mean(sq_error), std(sq_error), mean(l_inf_error));
end